### PR TITLE
`str(query_set)` returns extra quotes, this adds __str__ to queryset to prevent that

### PR DESCRIPTION
**Pull request by jtzero**
before:
```python
>>> import sakstig
>>> qs = sakstig.QuerySet([{"name": "alice", "sequence":1}]).execute("$.name")
>>> str(qs) == list(qs)[0]
False
>>> str(qs) == "'alice'"
True
>>> list(qs)[0] == "alice"
True
```
after:
```python
>>> import sakstig
>>> qs = sakstig.QuerySet([{"name": "alice", "sequence":1}]).execute("$.name")
>>> str(qs) == list(qs)[0]
True
>>> repr(qs) == "'alice'"
True
```

### CODE REVIEW

**Comment by redhog** [comment]
Wouldn't it be more correct if __str__ just did the same as / something similar to __repr__, that is, if the qs contains multiple items, separates them by newline?

```
def __str__(self):
    return "\n".join(str(item) for item in self)

```

**Comment by jtzero** [comment]
I think that would be inconsistent with how `str` works on other objects. I think one would reasonbly expect this to be True: 
```python
str(sakstig.QuerySet([{"ary": [1,2,3]}]).execute("$.ary")) == str([1,2,3])
```
as
```python
>>> str([1,2,3])
'[1, 2, 3]'
```

**Comment by redhog** [comment]
But that would still be true. What would differ would be the output of

    str(sakstig.QuerySet([{"ary": [1,2,3]}, {"ary": [4, 5, 6]}]).execute("$.ary"))

which in your implementation would be

    [[1,2,3], [4, 5, 6]]

and with mine

    [1,2,3]
    [4,5,6]

which is consistent with querysets being something else than lists.

**Comment by redhog** [comment]
Check out https://github.com/innovationgarage/sakstig/pull/4 (it has been merged into master). If the functionality doesn't implement what you need closely enough, just reopen this PR.

**Pull request closed without merging**
